/*
 * This file is generated by jOOQ.
 */
package ru.ivanovds.tasks.demo.entity.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer priority;
    private String description;
    private Long personId;

    public Task() {}

    public Task(Task value) {
        this.id = value.id;
        this.priority = value.priority;
        this.description = value.description;
        this.personId = value.personId;
    }

    public Task(
        Long id,
        Integer priority,
        String description,
        Long personId
    ) {
        this.id = id;
        this.priority = priority;
        this.description = description;
        this.personId = personId;
    }

    /**
     * Getter for <code>public.task.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.task.id</code>.
     */
    public Task setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.task.priority</code>.
     */
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * Setter for <code>public.task.priority</code>.
     */
    public Task setPriority(Integer priority) {
        this.priority = priority;
        return this;
    }

    /**
     * Getter for <code>public.task.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.task.description</code>.
     */
    public Task setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>public.task.person_id</code>.
     */
    public Long getPersonId() {
        return this.personId;
    }

    /**
     * Setter for <code>public.task.person_id</code>.
     */
    public Task setPersonId(Long personId) {
        this.personId = personId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Task other = (Task) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.priority == null) {
            if (other.priority != null)
                return false;
        }
        else if (!this.priority.equals(other.priority))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.personId == null) {
            if (other.personId != null)
                return false;
        }
        else if (!this.personId.equals(other.personId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.priority == null) ? 0 : this.priority.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.personId == null) ? 0 : this.personId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Task (");

        sb.append(id);
        sb.append(", ").append(priority);
        sb.append(", ").append(description);
        sb.append(", ").append(personId);

        sb.append(")");
        return sb.toString();
    }
}
