server:
  port: 8081
  servlet:
    context-path: /tasks

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl:
          auto: create
        default_schema: otk

logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: INFO