server:
  port: 8081
  servlet:
    context-path: /task

spring:
  liquibase:
    enabled: true
    liquibase-schema: public
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl:
          auto: none
        default_schema: public
