server:
  port: 8081
  servlet:
    context-path: /task

spring:
  liquibase:
    enabled: true
    liquibase-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: PandoraSQ123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl:
          auto: none
        default_schema: public

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /api-swagger
    enabled: true
