/*
 * This file is generated by jOOQ.
 */
package ru.ivanovds.tasks.demo.entity.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.ivanovds.tasks.demo.entity.tables.Task;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskRecord extends UpdatableRecordImpl<TaskRecord> implements Record4<Long, Integer, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.task.id</code>.
     */
    public TaskRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.task.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.task.priority</code>.
     */
    public TaskRecord setPriority(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.task.priority</code>.
     */
    public Integer getPriority() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.task.description</code>.
     */
    public TaskRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.task.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.task.person_id</code>.
     */
    public TaskRecord setPersonId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.task.person_id</code>.
     */
    public Long getPersonId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Integer, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Integer, String, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Task.TASK.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Task.TASK.PRIORITY;
    }

    @Override
    public Field<String> field3() {
        return Task.TASK.DESCRIPTION;
    }

    @Override
    public Field<Long> field4() {
        return Task.TASK.PERSON_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPriority();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Long component4() {
        return getPersonId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPriority();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Long value4() {
        return getPersonId();
    }

    @Override
    public TaskRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TaskRecord value2(Integer value) {
        setPriority(value);
        return this;
    }

    @Override
    public TaskRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TaskRecord value4(Long value) {
        setPersonId(value);
        return this;
    }

    @Override
    public TaskRecord values(Long value1, Integer value2, String value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskRecord
     */
    public TaskRecord() {
        super(Task.TASK);
    }

    /**
     * Create a detached, initialised TaskRecord
     */
    public TaskRecord(Long id, Integer priority, String description, Long personId) {
        super(Task.TASK);

        setId(id);
        setPriority(priority);
        setDescription(description);
        setPersonId(personId);
    }

    /**
     * Create a detached, initialised TaskRecord
     */
    public TaskRecord(ru.ivanovds.tasks.demo.entity.tables.pojos.Task value) {
        super(Task.TASK);

        if (value != null) {
            setId(value.getId());
            setPriority(value.getPriority());
            setDescription(value.getDescription());
            setPersonId(value.getPersonId());
        }
    }
}
