/*
 * This file is generated by jOOQ.
 */
package ru.ivanovds.tasks.demo.entity;


import ru.ivanovds.tasks.demo.entity.tables.Databasechangelog;
import ru.ivanovds.tasks.demo.entity.tables.Databasechangeloglock;
import ru.ivanovds.tasks.demo.entity.tables.Person;
import ru.ivanovds.tasks.demo.entity.tables.Task;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>public.task</code>.
     */
    public static final Task TASK = Task.TASK;
}
